### ISSUE TITLE
How to iterate through all tables?

### ISSUE THREAD

**Issue by emillaine** [jdfergason/swift-toml#2]
I have a use case where I would need to loop over all root-level tables to check whether each table contains a certain key. Currently this doesn't seem to be possible.

I was previously using [YamlSwift](https://github.com/behrang/YamlSwift), where this was possible using the `dictionary` getter:

```
for (key, value) in yaml.dictionary! {
    if let property = value["property"] {
        // use `key` and `property`
    }
}
```

It would be nice to have something similar in swift-toml, for example:

```
for (tableName, table) in toml.tables {
    if let property = try? table.double("property") {
        // use `tableName` and `property`
    }
}
```

**Comment by jdfergason** [comment]
I can see the use for this but it's not so straightforward to implement since swift-toml is basically storing key/values in a flat structure after it's parsed.  I'm working on a function that will allow you to grab all tables beneath a given key path.

To grab all tables at the root level:

```
for (tableName, table) in toml.tables() { ... }
```

or, to get all the tables nested within table1:

```
for (tableName, table) in toml.tables("table1") { ... } 
```

It will take me a day or two to get this functionality in.

**Comment by emillaine** [comment]
Awesome!

**Comment by jdfergason** [comment]
Added support for iterating over all tables at a given level with `tables(_: [String])` method in 85fc130580439c6e762c9588fd62ad892240f5a6 and created [v0.3.0 release](https://github.com/jdfergason/swift-toml/releases/tag/v0.3.0).

**Comment by emillaine** [comment]
Nice, thanks!
